"""Plan an identifier-schema migration (codebook refit). §15.6, §35B R4, ADR 0004.

    python pipelines/schema_migration.py --corpus export/corpus.jsonl --embeddings export/embeddings.npy \
        --ids-config configs/identifiers/ids_v2.yaml --codebook-version cb_v2.0 --out migrations/ids_v2

The single most dangerous operation in the system: every identifier, trie, dataset, and
checkpoint depends on the codebooks. This pipeline only PLANS. It refits the quantizer,
assigns every document its new identifier, and writes the artefacts the migration needs:

    codebooks/        the new frozen codebooks (hashed)
    mapping.jsonl     doc_uid, old semantic id, new semantic id
    trie/             the new schema's trie snapshot
    cutover.sql       registry rewrite with SCHEMA_MIGRATION aliases, for DBA review
    plan.json         escape rate, balance, and what fraction of documents move

Execution follows docs/runbooks/schema-migration.md: dual bundles live, double capacity,
two-person rule, rehearsed in staging on a full-size corpus copy first.
"""

from __future__ import annotations

import argparse
import json
import uuid
from pathlib import Path

import numpy as np
from sigil_core.config import load_yaml
from sigil_core.ids import SemanticId
from sigil_identifiers.assignment import PrefixCounter, escape_rate
from sigil_identifiers.quantizer import RQKMeans, codebook_io, occupancy_report
from sigil_trie import write

from services.trie_builder.main import corpus_snapshot_name


def plan(corpus: list[dict], embeddings: np.ndarray, ids_cfg: dict, codebook_version: str, out: Path,
         sample: int | None = None) -> dict:
    schema = ids_cfg["schema_version"]
    q = RQKMeans.from_config(ids_cfg)
    rng = np.random.default_rng(q.seed)
    n = len(corpus)
    fit_idx = rng.choice(n, min(n, sample or ids_cfg["quantizer"]["sample_size"]), replace=False)
    q.fit(embeddings[np.sort(fit_idx)])
    codes = q.encode(embeddings)
    order = sorted(range(n), key=lambda i: corpus[i]["doc_uid"])  # deterministic ordinal assignment
    counter = PrefixCounter()
    new = {}
    for i in order:
        new[i] = counter.allocate(codes[i])
    out.mkdir(parents=True, exist_ok=False)
    cb = codebook_io.save(q.codebooks, out / "codebooks", version=codebook_version, id_schema=schema)
    trie_path, trie_sha = write(new.values(), out / "trie", id_schema=schema, corpus_snapshot=corpus_snapshot_name())
    moved_l1 = 0
    with open(out / "mapping.jsonl", "w", encoding="utf-8") as f, open(out / "cutover.sql", "w", encoding="utf-8") as sql:
        sql.write("-- Generated by pipelines/schema_migration.py. Review, then run inside the cutover window.\n"
                  "BEGIN;\n")
        for i in order:
            old = corpus[i]["semantic_id"]
            moved_l1 += SemanticId.parse(old).codes[0] != new[i].codes[0]
            f.write(json.dumps({"doc_uid": corpus[i]["doc_uid"], "old": old, "new": str(new[i])}) + "\n")
            uid = str(uuid.UUID(corpus[i]["doc_uid"]))  # validated: it is interpolated into SQL
            sql.write("INSERT INTO identifier_aliases (old_semantic_id, id_schema_version, doc_uid, reason, created_at, "
                      "expires_at) SELECT semantic_id, id_schema_version, doc_uid, 'SCHEMA_MIGRATION', now(), "
                      f"now() + interval '30 days' FROM documents WHERE doc_uid = '{uid}';\n")
            sql.write(f"UPDATE documents SET semantic_id = '\\x{new[i].pack().hex()}', id_schema_version = '{schema}' "
                      f"WHERE doc_uid = '{uid}';\n")
        sql.write("COMMIT;\n")
    report = {
        "schema": schema, "codebooks": cb.version, "codebook_sha256": cb.sha256, "trie": str(trie_path),
        "trie_sha256": trie_sha, "documents": n, "escape_rate": escape_rate(new.values()),
        "level1_moved_share": moved_l1 / max(n, 1), "occupancy": occupancy_report(codes, q.k),
        "reconstruction_error": q.reconstruction_error(embeddings[: min(n, 50_000)]),
        "gates": {"escape_rate_ok": escape_rate(new.values()) < ids_cfg["thresholds"]["escape_rate_alarm"],
                  "l1_balance_ok": occupancy_report(codes, q.k)["l1_max_over_mean"] <= ids_cfg["quantizer"]["balance_max_ratio"]},
    }
    (out / "plan.json").write_text(json.dumps(report, indent=2))
    return report


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--corpus", required=True)
    ap.add_argument("--embeddings", required=True, help=".npy aligned row-for-row with --corpus")
    ap.add_argument("--ids-config", required=True)
    ap.add_argument("--codebook-version", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--dry-run", action="store_true", help="accepted for Makefile symmetry; this tool only plans")
    a = ap.parse_args(argv)
    corpus = [json.loads(x) for x in Path(a.corpus).read_text(encoding="utf-8").splitlines() if x.strip()]
    report = plan(corpus, np.load(a.embeddings), load_yaml(a.ids_config), a.codebook_version, Path(a.out))
    print(json.dumps({k: v for k, v in report.items() if k != "occupancy"}, indent=2))


if __name__ == "__main__":
    main()
